In [1]:
import pandas as pd
import numpy as np
import itertools
from scipy.stats import chi2_contingency
from conditional import csv_format_discrete
from scipy.stats import chi2

In [2]:
df = csv_format_discrete(r"C:\Users\User\Documents\GitHub\ML_FYP\dataset\Water_1000.dat")

In [3]:
df = df.head(n = 100)

In [4]:
#takes in a pandas dataframe, collects each column of the dataframe and combine it into a list
def split_(df):
    v = list(df)
    empty_0 = []
    for i in list(df):
        column_of_array = df[i].to_numpy()
        empty_0.append(column_of_array)
    return empty_0

In [5]:
split_(df)

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2,
        2, 2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0,
        1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0,
        0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1,
        2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [6]:
#this function essentially obtains all the combinations of the splitted df in nC2
def combinations_(df):
    empty_1 = []
    empty_2 = []
    v = split_(df) #call the function split_
    itertools_combinations = list((itertools.combinations(v, 2)))
    return itertools_combinations
#returns a list of combinations

In [7]:
combinations_(df)

[(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
  array([1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2,
         2, 2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0,
         1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0,
         0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1,
         2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1], dtype=int64)),
 (array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [8]:
#performs a chi2 test on every combinations in the list, then prints the output
def chi2bool(df):
    chi = chi2_contingency(df)
    chi_squared = chi[0]
    dof = chi[2]
    critical_value = chi2.ppf(0.95, dof)
    if chi[0] >  critical_value:
        print("since chi2 =", chi[0] , "is more than the critical value =" , critical_value , ", we reject the null hypothesis, dof=", dof) 
    else: 
        print("since chi2 =" , chi[0] , "is less than the critical value =" , critical_value , ", we do not reject the null hypothesis, dof=", dof)

In [9]:
def tolist(df):
    df = combinations_(df)
    df = np.array(df)
    df = df.tolist()
    return df

In [25]:
a = combinations_(df)
new_df = pd.DataFrame(a)
new_df

0  \
0    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
1    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
2    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
3    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
4    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
..                                                 ...   
491  [2, 2, 0, 1, 1, 2, 1, 2, 1, 2, 2, 0, 0, 1, 2, ...   
492  [2, 2, 0, 1, 1, 2, 1, 2, 1, 2, 2, 0, 0, 1, 2, ...   
493  [1, 1, 3, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, ...   
494  [1, 1, 3, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, ...   
495  [2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...   

                                                     1  
0    [1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 2, 1, 2, ...  
1    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
2    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
3    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
4    [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, ...  
..                                                 ...  
491  [2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...  
492  [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
493  [2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...  
494  [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
495  [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  

[496 rows x 2 columns]

In [11]:
b = a[0]
b
new_empty = []
for i in b:
    new_empty.append(i.tolist())
print(new_empty)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1]]


In [12]:
chi2bool(new_empty)

since chi2 = 41.87367867867868 is less than the critical value = 123.2252214533618 , we do not reject the null hypothesis, dof= 99


In [14]:
from pgmpy.estimators.CITests import chi_square

In [21]:
a

[(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
  array([1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2,
         2, 2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0,
         1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0,
         0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1,
         2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1], dtype=int64)),
 (array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [26]:
X = new_empty[0]
Y = new_empty[1]
chi_square(X=X, Y=Y, Z=[], data=new_df, boolean=False)

ValueError: Grouper and axis must be same length

[1,
 0,
 0,
 2,
 2,
 2,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 2,
 1,
 2,
 1,
 1,
 0,
 0,
 2,
 0,
 1,
 1,
 2,
 0,
 0,
 2,
 2,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 1]