In [66]:
import pandas as pd
# from tabulate import tabulate
import numpy as np
# import bnlearn as bn
import pgmpy
import itertools
from scipy.stats import chi2_contingency
from scipy.stats import power_divergence
from scipy.stats import chisquare
# from pgmpy.estimators.CITests import chi_square
# from pgmpy.factors.continuous.discretize import BaseDiscretizer

In [2]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])

#returns the csv_file in a pandas dataframe, formatted properly, discrete dataset only

In [3]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])


In [4]:
def gaussian_reader(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df

In [5]:
def chi_square_CI(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1])
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t])
    for x,y,i in zip(empty_1, empty_2, empty):
        chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5


In [77]:
def chi_square_CI(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty_0 = []
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in list(df):
        array = df[i].to_numpy()
        empty_0.append([i,array]) #gives the array of the columns of the thing
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1])
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t])
    for x,y,i in zip(empty_1, empty_2, empty):
        chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5

In [91]:
def new_chi(df):
    test = []
    for i in list(df):
        array = df[i].to_numpy()
        test.append(array)
    return test

In [102]:
test = new_chi(df)
test_2 = np.array([test[0], test[1]])
test_2

array([[3, 0, 0, 1, 3, 1, 2, 2],
       [1, 2, 2, 2, 2, 1, 1, 0]], dtype=int64)

In [100]:
chisquare(test_2)

Power_divergenceResult(statistic=array([1.        , 2.        , 2.        , 0.33333333, 0.2       ,
       0.        , 0.33333333, 2.        ]), pvalue=array([0.31731051, 0.15729921, 0.15729921, 0.56370286, 0.65472085,
       1.        , 0.56370286, 0.15729921]))

In [78]:
test = []
for i in list(df):
    array = df[i].to_numpy()
    test.append([i,array])

In [90]:
test

In [72]:
df

A  B  C  D  E
1  3  1  2  3  1
2  0  2  3  2  2
3  0  2  3  4  3
4  1  2  2  3  0
5  3  2  3  4  0
6  1  1  3  4  4
7  2  1  1  3  4
8  2  0  2  0  2

In [59]:
df = csv_format_discrete(r"C:\Users\User\Documents\GitHub\ML_FYP\dataset\test_2.dat")
v = list(df)

In [60]:
empty = []
empty_1 = []
empty_2 = []
empty_3 = []
empty_4 = []
empty_5 = []
itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
for i in itertools_combinations:
    empty_1.append(i[0])
    empty_2.append(i[1])
# for t in range(len(itertools_combinations)):
#     empty.append(itertools_combinations[t])
# for x,y,i in zip(empty_1, empty_2, empty):
#     chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
#     empty_3.append([i , chisquare])
# for value in range(len(empty_3)):
#     empty_4.append(value)
# for x,y in zip(empty_4, empty_3):
#     empty_5.append([x,y])
# print(empty_5)

[[0, [('A', 'B'), (6.0, 0.42319008112684364, 6)]], [1, [('A', 'C'), (6.0, 0.42319008112684364, 6)]], [2, [('A', 'D'), (8.0, 0.5341462169096916, 9)]], [3, [('A', 'E'), (12.0, 0.44567964136461097, 12)]], [4, [('B', 'C'), (4.055555555555555, 0.3985394322295418, 4)]], [5, [('B', 'D'), (9.777777777777777, 0.13432763270881842, 6)]], [6, [('B', 'E'), (11.0, 0.20169919870252867, 8)]], [7, [('C', 'D'), (8.88888888888889, 0.1799239866069569, 6)]], [8, [('C', 'E'), (6.333333333333334, 0.6099475869625752, 8)]], [9, [('D', 'E'), (10.666666666666668, 0.5576805436358871, 12)]]]


In [61]:
for t in range(len(itertools_combinations)):
    empty.append(itertools_combinations[t])

In [70]:
np.array([empty_1, empty_2])

array([['A', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'D'],
       ['B', 'C', 'D', 'E', 'C', 'D', 'E', 'D', 'E', 'E']], dtype='<U1')

In [71]:
for x,y,i in zip(empty_1, empty_2, empty):
    empty_array = np.array([empty_1, empty_2])
    chisquare = chisquare(empty_array)

ValueError: could not convert string to float: 'A'

In [65]:
chisquare

(10.666666666666668, 0.5576805436358871, 12)

In [ ]:
obs = 

In [32]:
obs = np.array([
               [3,0,0,1,3,1,2,2], 
               [1,2,2,2,2,1,1,0]])
obs

array([[3, 0, 0, 1, 3, 1, 2, 2],
       [1, 2, 2, 2, 2, 1, 1, 0]])

In [33]:
res = chi2_contingency(obs)   


In [34]:
res

(7.838005050505051,
 0.3470951089625462,
 7,
 array([[2.08695652, 1.04347826, 1.04347826, 1.56521739, 2.60869565,
         1.04347826, 1.56521739, 1.04347826],
        [1.91304348, 0.95652174, 0.95652174, 1.43478261, 2.39130435,
         0.95652174, 1.43478261, 0.95652174]]))

In [43]:
test = chisquare(obs)
k = test.statistic

In [ ]:
v = list(df.loc[:,"Seven"])

In [ ]:
k = power_divergence(v, lambda_="log-likelihood")
#returns statistics, p-value

In [30]:
k_ = list(k)
k_

[2097.253052117013, 1.0]

In [31]:
30/66

0.45454545454545453