In [28]:
import pandas as pd
# from tabulate import tabulate
import numpy as np
# import bnlearn as bn
import pgmpy
import itertools
from scipy.stats import chi2_contingency #check for independence between 2 variables
from scipy.stats import power_divergence

from pgmpy.estimators.CITests import chi_square
# from pgmpy.factors.continuous.discretize import BaseDiscretizer

In [3]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])

#returns the csv_file in a pandas dataframe, formatted properly, discrete dataset only

In [32]:
df = csv_format_discrete(r"C:\Users\User\Documents\GitHub\ML_FYP\dataset\Water_1000.dat")

In [5]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])


In [6]:
def gaussian_reader(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df

In [76]:
df['One']

1       1
2       1
3       1
4       1
5       1
       ..
996     1
997     1
998     1
999     1
1000    1
Name: One, Length: 1000, dtype: int64

In [73]:
new_test = []
for i in list(df):
    a = pd.DataFrame(df.loc[:, i])
    new_test.append(a)
    
new_test[1]

Two
1       1
2       0
3       0
4       2
5       2
...   ...
996     1
997     0
998     1
999     1
1000    1

[1000 rows x 1 columns]

In [99]:
df

One  Two  Three  Four  Five  Six  Seven  Eight  Nine  Ten  ...  \
1       1    1      1     1     1    1      1      0     1    1  ...   
2       1    0      1     1     1    1      1      1     1    1  ...   
3       1    0      1     1     1    0      0      0     1    0  ...   
4       1    2      1     1     1    1      1      0     1    2  ...   
5       1    2      1     1     1    1      1      1     1    1  ...   
...   ...  ...    ...   ...   ...  ...    ...    ...   ...  ...  ...   
996     1    1      1     1     1    1      1      1     1    2  ...   
997     1    0      1     1     1    1      1      1     1    1  ...   
998     1    1      1     1     1    0      0      1     1    1  ...   
999     1    1      1     1     1    0      0      0     1    1  ...   
1000    1    1      1     1     1    1      1      1     1    1  ...   

      TwentyThree  TwentyFour  TwentyFive  TwentySix  TwentySeven  \
1               1           0           2          0            1   
2               1           0           2          0            1   
3               2           0           2          0            2   
4               1           0           3          0            1   
5               1           0           2          0            1   
...           ...         ...         ...        ...          ...   
996             1           0           2          0            1   
997             1           0           2          0            1   
998             2           1           2          1            3   
999             1           0           2          0            1   
1000            1           0           2          0            1   

      TwentyEight  TwentyNine  Thirty  ThirtyOne  ThirtyTwo  
1               1           2       1          2          0  
2               1           2       1          2          1  
3               0           0       3          2          0  
4               1           1       0          3          0  
5               1           1       1          2          0  
...           ...         ...     ...        ...        ...  
996             1           0       1          2          0  
997             0           1       0          2          0  
998             0           1       2          2          0  
999             0           2       3          2          1  
1000            1           1       0          2          0  

[1000 rows x 32 columns]

In [101]:
chi_square(X='Five', Y='TwentyThree', Z=[], data=df, significance_level=0.95, boolean=False)

(2.3995410227449856, 0.49372006690246006, 3)

In [7]:
def chi_square_CI(df):
#returns a tuple(chi, p_value, dof) if boolean = false
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1])
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t])
    for x,y,i in zip(empty_1, empty_2, empty):
        chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5


In [105]:
chi_square_CI(df)

[[0, [('One', 'Two'), (0.0, 1.0, 0)]],
 [1, [('One', 'Three'), (0.0, 1.0, 0)]],
 [2, [('One', 'Four'), (0.0, 1.0, 0)]],
 [3, [('One', 'Five'), (0.0, 1.0, 0)]],
 [4, [('One', 'Six'), (0.0, 1.0, 0)]],
 [5, [('One', 'Seven'), (0.0, 1.0, 0)]],
 [6, [('One', 'Eight'), (0.0, 1.0, 0)]],
 [7, [('One', 'Nine'), (0.0, 1.0, 0)]],
 [8, [('One', 'Ten'), (0.0, 1.0, 0)]],
 [9, [('One', 'Eleven'), (0.0, 1.0, 0)]],
 [10, [('One', 'Twelve'), (0.0, 1.0, 0)]],
 [11, [('One', 'Thirteen'), (0.0, 1.0, 0)]],
 [12, [('One', 'Fourteen'), (0.0, 1.0, 0)]],
 [13, [('One', 'Fifteen'), (0.0, 1.0, 0)]],
 [14, [('One', 'Sixteen'), (0.0, 1.0, 0)]],
 [15, [('One', 'Seventeen'), (0.0, 1.0, 0)]],
 [16, [('One', 'Eighteen'), (0.0, 1.0, 0)]],
 [17, [('One', 'Nineteen'), (0.0, 1.0, 0)]],
 [18, [('One', 'Twenty'), (0.0, 1.0, 0)]],
 [19, [('One', 'TwentyOne'), (0.0, 1.0, 0)]],
 [20, [('One', 'TwentyTwo'), (0.0, 1.0, 0)]],
 [21, [('One', 'TwentyThree'), (0.0, 1.0, 0)]],
 [22, [('One', 'TwentyFour'), (0.0, 1.0, 0)]],
 [23, [('On

In [37]:
chi_square(X='Two', Y='ThirtyTwo', Z=[], data=df, significance_level=0.95, boolean=False)

(0.009359824085937909, 0.9953310216824551, 2)

In [34]:
chi_square_CI(df)

[[0, [('One', 'Two'), (0.0, 1.0, 0)]],
 [1, [('One', 'Three'), (0.0, 1.0, 0)]],
 [2, [('One', 'Four'), (0.0, 1.0, 0)]],
 [3, [('One', 'Five'), (0.0, 1.0, 0)]],
 [4, [('One', 'Six'), (0.0, 1.0, 0)]],
 [5, [('One', 'Seven'), (0.0, 1.0, 0)]],
 [6, [('One', 'Eight'), (0.0, 1.0, 0)]],
 [7, [('One', 'Nine'), (0.0, 1.0, 0)]],
 [8, [('One', 'Ten'), (0.0, 1.0, 0)]],
 [9, [('One', 'Eleven'), (0.0, 1.0, 0)]],
 [10, [('One', 'Twelve'), (0.0, 1.0, 0)]],
 [11, [('One', 'Thirteen'), (0.0, 1.0, 0)]],
 [12, [('One', 'Fourteen'), (0.0, 1.0, 0)]],
 [13, [('One', 'Fifteen'), (0.0, 1.0, 0)]],
 [14, [('One', 'Sixteen'), (0.0, 1.0, 0)]],
 [15, [('One', 'Seventeen'), (0.0, 1.0, 0)]],
 [16, [('One', 'Eighteen'), (0.0, 1.0, 0)]],
 [17, [('One', 'Nineteen'), (0.0, 1.0, 0)]],
 [18, [('One', 'Twenty'), (0.0, 1.0, 0)]],
 [19, [('One', 'TwentyOne'), (0.0, 1.0, 0)]],
 [20, [('One', 'TwentyTwo'), (0.0, 1.0, 0)]],
 [21, [('One', 'TwentyThree'), (0.0, 1.0, 0)]],
 [22, [('One', 'TwentyFour'), (0.0, 1.0, 0)]],
 [23, [('On

In [10]:
def new_chi(df):
    test = []
    for i in list(df):
        array = df[i].to_numpy()
        test.append(array)
    return test

In [11]:
test = new_chi(df)
a = test[0].tolist()
b = test[1].tolist()
test_2 = np.array([a, b])
test_2

array([[3, 0, 0, 1, 3, 1, 2, 2, 2],
       [3, 2, 2, 2, 4, 1, 1, 2, 3]])

In [12]:
chi2_contingency(test_2)[3]

array([[2.47058824, 0.82352941, 0.82352941, 1.23529412, 2.88235294,
        0.82352941, 1.23529412, 1.64705882, 2.05882353],
       [3.52941176, 1.17647059, 1.17647059, 1.76470588, 4.11764706,
        1.17647059, 1.76470588, 2.35294118, 2.94117647]])

In [13]:
chi2empty = []

In [14]:
new_array

NameError: name 'new_array' is not defined

In [15]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
#     chi2empty.append(chisquare)

NameError: name 'empty_1' is not defined

In [16]:
test = []
for i in list(df):
    array = df[i].to_numpy()
    test.append([i,array])

In [17]:
test

[['A', array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64)],
 ['B', array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64)],
 ['C', array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64)],
 ['D', array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64)],
 ['E', array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)]]

In [18]:
df

A  B  C  D  E
1  3  3  2  3  1
2  0  2  3  2  2
3  0  2  3  4  3
4  1  2  2  3  0
5  3  4  3  4  0
6  1  1  3  4  4
7  2  1  1  3  4
8  2  2  2  0  2
9  2  3  1  3  2

In [19]:
v = list(df)

In [20]:
v = list(df)
empty_0 = []
empty = []
empty_1 = []
empty_2 = []
empty_3 = []
empty_4 = []
empty_5 = []
itertools_combinations = list(itertools.combinations(v, 2))
#finds every possible combination of list(df)
for i in list(df):
    column_of_array = df[i].to_numpy()
    empty_0.append(column_of_array) #gives the array of the columns of the thing
itertools_combinations_lists = list(itertools.combinations(empty_0,2))
for lists in itertools_combinations_lists:
    empty_1.append(list)
for t in range(len(itertools_combinations)):
    empty.append(itertools_combinations[t]) #appends the length of the combinations into a list
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])
for value in range(len(empty_3)):
    empty_4.append(value)
for x,y in zip(empty_4, empty_3):
    empty_5.append([x,y])

In [21]:
empty_0


[array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
 array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)]

In [22]:
test = []
itertools_combinations_lists = list(itertools.combinations(empty_0,2))
for i in itertools_combinations_lists:
    test.append(i)
test

[(array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
  array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)),
 (array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64)),
 (array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64)),
 (array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)),
 (array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64)),
 (array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)),
 (array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64),
  array([1, 2, 3, 0, 0

In [23]:
test = []
for i in empty_0:
    k = i.tolist()
    test.append(k)
test
#for 1,2,...,n in empty_0, append to n number of lists
# for j in range(len(empty_0)):
#     for i in empty_0:
#         print(j)
    
#         empty_1.append(i[0])
#         empty_2.append(i[1])

[[3, 0, 0, 1, 3, 1, 2, 2, 2],
 [3, 2, 2, 2, 4, 1, 1, 2, 3],
 [2, 3, 3, 2, 3, 3, 1, 2, 1],
 [3, 2, 4, 3, 4, 4, 3, 0, 3],
 [1, 2, 3, 0, 0, 4, 4, 2, 2]]

In [24]:
empty_0, empty_1, empty_2

([array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
  array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)],
 [list, list, list, list, list, list, list, list, list, list],
 [])

In [25]:
test = []
for i in list(df):
    column_of_array = df[i].to_numpy()
    test.append(column_of_array)
#     empty_0.append(array)
test

[array([3, 0, 0, 1, 3, 1, 2, 2, 2], dtype=int64),
 array([3, 2, 2, 2, 4, 1, 1, 2, 3], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2, 1], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0, 3], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2, 2], dtype=int64)]

In [26]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])

In [ ]:
empty_3

In [ ]:
np.array([empty_1, empty_2])

In [ ]:
test = []
for i in list(df):
    array = df[i].to_numpy()
#     print(array)
    test.append([array])

In [ ]:
weird = []
for i in test:
    for k in i:
        weird.append(k)

In [ ]:
weird[0].tolist()

In [ ]:
for x,y,i in zip(empty_1, empty_2, empty):
    empty_array = np.array([empty_1, empty_2])
    chisquare = chisquare(empty_array)