In [115]:
import pandas as pd
# from tabulate import tabulate
import numpy as np
# import bnlearn as bn
import pgmpy
import itertools
from scipy.stats import chi2_contingency #check for independence between 2 variables
from scipy.stats import power_divergence
# from pgmpy.estimators.CITests import chi_square
# from pgmpy.factors.continuous.discretize import BaseDiscretizer

In [2]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])

#returns the csv_file in a pandas dataframe, formatted properly, discrete dataset only

In [3]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])


In [4]:
def gaussian_reader(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df

In [5]:
def chi_square_CI(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1])
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t])
    for x,y,i in zip(empty_1, empty_2, empty):
        chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5


In [118]:
def chi2(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty_0 = []
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in list(df):
        column_of_array = df[i].to_numpy()
        empty_0.append(array) #gives the array of the columns of the thing
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1]) #appends combinations into each list
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t]) #appends the length of the combinations into a list
    for x,y,i in zip(empty_1, empty_2, empty):
        new_array = np.array([empty_1,empty_2])
        chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5

In [119]:
chi2(df)

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'int'

In [91]:
def new_chi(df):
    test = []
    for i in list(df):
        array = df[i].to_numpy()
        test.append(array)
    return test

In [108]:
test = new_chi(df)
a = test[0].tolist()
b = test[1].tolist()
test_2 = np.array([a, b])
test_2

array([[3, 0, 0, 1, 3, 1, 2, 2],
       [1, 2, 2, 2, 2, 1, 1, 0]])

In [114]:
chi2_contingency(test_2)[3]

array([[2.08695652, 1.04347826, 1.04347826, 1.56521739, 2.60869565,
        1.04347826, 1.56521739, 1.04347826],
       [1.91304348, 0.95652174, 0.95652174, 1.43478261, 2.39130435,
        0.95652174, 1.43478261, 0.95652174]])

In [146]:
chi2empty = []

In [151]:
new_array

array([['A', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'D'],
       ['B', 'C', 'D', 'E', 'C', 'D', 'E', 'D', 'E', 'E']], dtype='<U1')

In [150]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
#     chi2empty.append(chisquare)

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'int'

In [78]:
test = []
for i in list(df):
    array = df[i].to_numpy()
    test.append([i,array])

In [90]:
test

In [72]:
df

A  B  C  D  E
1  3  1  2  3  1
2  0  2  3  2  2
3  0  2  3  4  3
4  1  2  2  3  0
5  3  2  3  4  0
6  1  1  3  4  4
7  2  1  1  3  4
8  2  0  2  0  2

In [59]:
df = csv_format_discrete(r"C:\Users\User\Documents\GitHub\ML_FYP\dataset\test_2.dat")
v = list(df)

In [176]:
v = list(df)
empty_0 = []
empty = []
empty_1 = []
empty_2 = []
empty_3 = []
empty_4 = []
empty_5 = []
itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
for i in list(df):
    column_of_array = df[i].to_numpy()
    empty_0.append(column_of_array) #gives the array of the columns of the thing
for i in empty_0:
    empty_1.append(i[0])
    empty_2.append(i[1]) #appends combinations into each list
for t in range(len(itertools_combinations)):
    empty.append(itertools_combinations[t]) #appends the length of the combinations into a list
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])
for value in range(len(empty_3)):
    empty_4.append(value)
for x,y in zip(empty_4, empty_3):
    empty_5.append([x,y])

In [191]:
empty_0

[array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
 array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)]

In [190]:
test = []
for i in empty_0:
    k = i.tolist()
    test.append(k)
test
#for 1,2,...,n in empty_0, append to n number of lists
# for j in range(len(empty_0)):
#     for i in empty_0:
#         print(j)
    
#         empty_1.append(i[0])
#         empty_2.append(i[1])

[[3, 0, 0, 1, 3, 1, 2, 2],
 [1, 2, 2, 2, 2, 1, 1, 0],
 [2, 3, 3, 2, 3, 3, 1, 2],
 [3, 2, 4, 3, 4, 4, 3, 0],
 [1, 2, 3, 0, 0, 4, 4, 2]]

In [182]:
empty_0, empty_1, empty_2

([array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)],
 [3, 1, 2, 3, 1],
 [0, 2, 3, 2, 2])

In [175]:
test = []
for i in list(df):
    column_of_array = df[i].to_numpy()
    test.append(column_of_array)
#     empty_0.append(array)
test

[array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
 array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)]

In [159]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])

In [160]:
empty_3

[[('A', 'B'),
  (0.0, 1.0, 4, array([[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.]]))],
 [('A', 'C'),
  (0.0, 1.0, 4, array([[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.]]))],
 [('A', 'D'),
  (0.0, 1.0, 4, array([[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.]]))],
 [('A', 'E'),
  (0.0, 1.0, 4, array([[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.]]))],
 [('B', 'C'),
  (0.0, 1.0, 4, array([[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.]]))]]

In [70]:
np.array([empty_1, empty_2])

array([['A', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'D'],
       ['B', 'C', 'D', 'E', 'C', 'D', 'E', 'D', 'E', 'E']], dtype='<U1')

In [135]:
test = []
for i in list(df):
    array = df[i].to_numpy()
#     print(array)
    test.append([array])

In [142]:
weird = []
for i in test:
    for k in i:
        weird.append(k)

In [145]:
weird[0].tolist()

[3, 0, 0, 1, 3, 1, 2, 2]

In [120]:
for x,y,i in zip(empty_1, empty_2, empty):
    empty_array = np.array([empty_1, empty_2])
    chisquare = chisquare(empty_array)

ValueError: could not convert string to float: 'A'