In [8]:
import pandas as pd
# from tabulate import tabulate
import numpy as np
# import bnlearn as bn
import pgmpy
import itertools
from scipy.stats import chi2_contingency #check for independence between 2 variables
from scipy.stats import power_divergence
# from pgmpy.estimators.CITests import chi_square
# from pgmpy.factors.continuous.discretize import BaseDiscretizer

In [14]:
df = csv_format_discrete(r"C:\Users\User\Documents\GitHub\ML_FYP\dataset\test_2.dat")


In [9]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])

#returns the csv_file in a pandas dataframe, formatted properly, discrete dataset only

In [10]:
def csv_format_discrete(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df.drop([0])


In [11]:
def gaussian_reader(csv_file):
    df = pd.read_csv(csv_file, sep="\s+")
    return df

In [12]:
def chi_square_CI(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1])
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t])
    for x,y,i in zip(empty_1, empty_2, empty):
        chisquare = chi_square(X=x, Y=y, Z=[], data=df, significance_level=0.95, boolean=False) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5


In [13]:
def chi2(df):
#the null hypothesis is that they are independent of each other
#if true, the p_value is higher than the significance test, we do not reject the null hypothesis
#if false, the p_value is lower than the significance test, we reject the null hypothesis
    v = list(df)
    empty_0 = []
    empty = []
    empty_1 = []
    empty_2 = []
    empty_3 = []
    empty_4 = []
    empty_5 = []
    itertools_combinations = list(itertools.combinations(v, 2)) #finds every possible combination of list(df)
    for i in list(df):
        column_of_array = df[i].to_numpy()
        empty_0.append(array) #gives the array of the columns of the thing
    for i in itertools_combinations:
        empty_1.append(i[0])
        empty_2.append(i[1]) #appends combinations into each list
    for t in range(len(itertools_combinations)):
        empty.append(itertools_combinations[t]) #appends the length of the combinations into a list
    for x,y,i in zip(empty_1, empty_2, empty):
        new_array = np.array([empty_1,empty_2])
        chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
        empty_3.append([i , chisquare])
    for value in range(len(empty_3)):
        empty_4.append(value)
    for x,y in zip(empty_4, empty_3):
        empty_5.append([x,y])
    return empty_5

In [15]:
chi2(df)

NameError: name 'array' is not defined

In [16]:
def new_chi(df):
    test = []
    for i in list(df):
        array = df[i].to_numpy()
        test.append(array)
    return test

In [17]:
test = new_chi(df)
a = test[0].tolist()
b = test[1].tolist()
test_2 = np.array([a, b])
test_2

array([[3, 0, 0, 1, 3, 1, 2, 2],
       [1, 2, 2, 2, 2, 1, 1, 0]])

In [18]:
chi2_contingency(test_2)[3]

array([[2.08695652, 1.04347826, 1.04347826, 1.56521739, 2.60869565,
        1.04347826, 1.56521739, 1.04347826],
       [1.91304348, 0.95652174, 0.95652174, 1.43478261, 2.39130435,
        0.95652174, 1.43478261, 0.95652174]])

In [19]:
chi2empty = []

In [20]:
new_array

NameError: name 'new_array' is not defined

In [21]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
#     chi2empty.append(chisquare)

NameError: name 'empty_1' is not defined

In [22]:
test = []
for i in list(df):
    array = df[i].to_numpy()
    test.append([i,array])

In [23]:
test

[['A', array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64)],
 ['B', array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64)],
 ['C', array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64)],
 ['D', array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64)],
 ['E', array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)]]

In [24]:
df

A  B  C  D  E
1  3  1  2  3  1
2  0  2  3  2  2
3  0  2  3  4  3
4  1  2  2  3  0
5  3  2  3  4  0
6  1  1  3  4  4
7  2  1  1  3  4
8  2  0  2  0  2

In [25]:
v = list(df)

In [26]:
v = list(df)
empty_0 = []
empty = []
empty_1 = []
empty_2 = []
empty_3 = []
empty_4 = []
empty_5 = []
itertools_combinations = list(itertools.combinations(v, 2))
#finds every possible combination of list(df)
for i in list(df):
    column_of_array = df[i].to_numpy()
    empty_0.append(column_of_array) #gives the array of the columns of the thing
itertools_combinations_lists = list(itertools.combinations(empty_0,2))
for lists in itertools_combinations_lists:
    empty_1.append(list)
for t in range(len(itertools_combinations)):
    empty.append(itertools_combinations[t]) #appends the length of the combinations into a list
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])
for value in range(len(empty_3)):
    empty_4.append(value)
for x,y in zip(empty_4, empty_3):
    empty_5.append([x,y])

In [27]:
empty_0


[array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
 array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)]

In [28]:
test = []
itertools_combinations_lists = list(itertools.combinations(empty_0,2))
for i in itertools_combinations_lists:
    test.append(i)
test

[(array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64)),
 (array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)),
 (array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64)),
 (array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64)),
 (array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)),
 (array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64)),
 (array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)),
 (array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64))]

In [29]:
test = []
for i in empty_0:
    k = i.tolist()
    test.append(k)
test
#for 1,2,...,n in empty_0, append to n number of lists
# for j in range(len(empty_0)):
#     for i in empty_0:
#         print(j)
    
#         empty_1.append(i[0])
#         empty_2.append(i[1])

[[3, 0, 0, 1, 3, 1, 2, 2],
 [1, 2, 2, 2, 2, 1, 1, 0],
 [2, 3, 3, 2, 3, 3, 1, 2],
 [3, 2, 4, 3, 4, 4, 3, 0],
 [1, 2, 3, 0, 0, 4, 4, 2]]

In [30]:
empty_0, empty_1, empty_2

([array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
  array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
  array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
  array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
  array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)],
 [list, list, list, list, list, list, list, list, list, list],
 [])

In [31]:
test = []
for i in list(df):
    column_of_array = df[i].to_numpy()
    test.append(column_of_array)
#     empty_0.append(array)
test

[array([3, 0, 0, 1, 3, 1, 2, 2], dtype=int64),
 array([1, 2, 2, 2, 2, 1, 1, 0], dtype=int64),
 array([2, 3, 3, 2, 3, 3, 1, 2], dtype=int64),
 array([3, 2, 4, 3, 4, 4, 3, 0], dtype=int64),
 array([1, 2, 3, 0, 0, 4, 4, 2], dtype=int64)]

In [32]:
for x,y,i in zip(empty_1, empty_2, empty):
    new_array = np.array([empty_1,empty_2])
    chisquare = chi2_contingency(new_array) #returns chi, p_value, dof
    empty_3.append([i , chisquare])

In [33]:
empty_3

[]

In [34]:
np.array([empty_1, empty_2])

C:\Users\User\AppData\Local\Temp\ipykernel_14176\254271885.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([empty_1, empty_2])


array([list([<class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>, <class 'list'>]),
       list([])], dtype=object)

In [35]:
test = []
for i in list(df):
    array = df[i].to_numpy()
#     print(array)
    test.append([array])

In [36]:
weird = []
for i in test:
    for k in i:
        weird.append(k)

In [37]:
weird[0].tolist()

[3, 0, 0, 1, 3, 1, 2, 2]

In [38]:
for x,y,i in zip(empty_1, empty_2, empty):
    empty_array = np.array([empty_1, empty_2])
    chisquare = chisquare(empty_array)